<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>48b31cab-8da8-481d-9524-87329f606b5f</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup>
  <SpaRoot>ClientApp\</SpaRoot>
</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>

<Target Name="BuildAngularForPublish" BeforeTargets="Build" Condition="'$(Configuration)' == 'Release' and '$(BuildAngular)' != 'false'">
  <Message Importance="high" Text="Building Angular app before .NET publish..." />

  <Exec WorkingDirectory="$(SpaRoot)" Command="npm ci" />

  <RemoveDir Directories="$(MSBuildProjectDirectory)\wwwroot" />
  <MakeDir Directories="$(MSBuildProjectDirectory)\wwwroot" />

  <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build -- --configuration production --output-path ../wwwroot" />
</Target>

</Project>
